//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTaskForNetDeveloperPosition
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchiveOfRequests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArchiveOfRequests()
        {
            this.UrlSiteMap = new HashSet<UrlSiteMap>();
        }
    
        public int IdArchiveOfRequests { get; set; }
        public string NameUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrlSiteMap> UrlSiteMap { get; set; }
    }
}
