//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTaskForNetDeveloperPosition
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageInfo
    {
        public int IdPageInfo { get; set; }
        public Nullable<int> SitemapId { get; set; }
        public Nullable<long> WebsiteLoadingSpeed { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<System.DateTime> PageTestDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<System.TimeSpan> Elapsed { get; set; }
    }
}
