//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTaskForNetDeveloperPosition
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlSiteMap
    {
        public int IdSitemap { get; set; }
        public Nullable<int> ArchiveOfRequestsId { get; set; }
        public string NameSite { get; set; }
    
        public virtual ArchiveOfRequests ArchiveOfRequests { get; set; }
    }
}
